### ISSUE TITLE
Add Readme.md with description

### ISSUE THREAD

**Issue by EwoutH** [gillesvangestel/ConvertWhatsAppToSignal#1]
First of all, awesome work!

Could you add a `Readme.md` file with a short description about what the software does, how to install it and how to use it? This will make it easier for unexperienced users to use it!

**Comment by gillesvangestel** [comment]
Great suggestion! I added a readme explaining the basic outline of the process. Please let me know if you have any suggestions on how to make the readme more understandable or any other suggestions you can come up with ;)

**Comment by EwoutH** [comment]
Looks great, thanks!
